/*
 * AI-Provenance:
 *   model: Claude Opus 5
 *   harness: Cursor
 *   edited-by: Claude Fable 5.1 (Claude Code)
 */
// GENERATED by scripts/flutter-examples.mjs — run `npm run examples:generate`.
//
// Committed so that `next build` can tell a stale bundle from a fresh one
// without having the Flutter SDK available. `npm run examples:check` fails
// the build when this drifts from the MDX.

export interface FlutterExample {
  /** The widget the island mounts. */
  preview: string
  /** How many Dart fences the snippet is made of. */
  files: number
  /** Pages the snippet appears on, for error messages. */
  docs: string[]
  /** Docs-only `Docs*` widgets the snippet uses, if any. */
  helpers?: string[]
}

export const flutterExamples: Record<string, FlutterExample> = {
  "00644560f554": { preview: "WizardForm", files: 3, docs: ["docs/subforms.mdx"], helpers: ["DocsActions","DocsDropdownField","DocsSubmitButton","DocsSwitchField","DocsTextField"] },
  "047778d0ab54": { preview: "SignupForm", files: 3, docs: ["docs/first-form.mdx","docs_app/content/landing/signup.mdx"] },
  "18570b69c83d": { preview: "UsernameAvailabilityForm", files: 2, docs: ["docs/async-validation.mdx","docs_app/content/landing/async.mdx"], helpers: ["DocsFailureBanner","DocsFieldStatus","DocsHint","DocsSubmitButton","DocsTextField"] },
  "1cbd6ee93f33": { preview: "KitchenSinkForm", files: 3, docs: ["docs/rendering.mdx"] },
  "2440ae7a9f0c": { preview: "DraftForm", files: 2, docs: ["docs/form-state.mdx"], helpers: ["DocsActions","DocsFailureBanner","DocsFormStatus","DocsHint","DocsSubmitButton","DocsTextField"] },
  "24da91a8b29c": { preview: "PizzaOrderForm", files: 2, docs: ["docs/fields.mdx"], helpers: ["DocsActions","DocsChipsField","DocsDropdownField","DocsSubmitButton","DocsSwitchField","DocsTextField"] },
  "2f9e8cdfae25": { preview: "GuestListForm", files: 2, docs: ["docs/subforms.mdx"], helpers: ["DocsActions","DocsSubmitButton","DocsTextField"] },
  "5276a0a4f33c": { preview: "FocusForm", files: 2, docs: ["docs/focus.mdx"], helpers: ["DocsActions","DocsSubmitButton","DocsTextField"] },
  "5cef6df3c4e9": { preview: "StateInspector", files: 2, docs: ["docs/concepts.mdx"], helpers: ["DocsActions","DocsTextField"] },
  "833e51744528": { preview: "OrderTotalForm", files: 2, docs: ["docs/cross-field.mdx"], helpers: ["DocsTextField"] },
  "9e1503fddf0c": { preview: "PasswordForm", files: 2, docs: ["docs/cross-field.mdx"], helpers: ["DocsTextField"] },
  "c40898fc28c3": { preview: "HeroSignupForm", files: 1, docs: ["docs_app/content/landing/hero.mdx"], helpers: ["DocsActions","DocsHint","DocsSubmitButton","DocsSwitchField","DocsTextField"] },
  "c513edd2c993": { preview: "PasswordRulesForm", files: 2, docs: ["docs/validators.mdx"], helpers: ["DocsTextField"] },
  "e0753cbd3d5d": { preview: "ProfileForm", files: 2, docs: ["docs/server-errors.mdx"], helpers: ["DocsActions","DocsHint","DocsSubmitButton","DocsTextField"] },
  "f295a159666b": { preview: "ValidationModesDemo", files: 2, docs: ["docs/validation-modes.mdx","docs_app/content/landing/modes.mdx"], helpers: ["DocsActions","DocsHint","DocsSubmitButton","DocsTextField"] },
  "f733c75e06e6": { preview: "PrefillDemo", files: 2, docs: ["docs/lifecycle.mdx"], helpers: ["DocsActions","DocsFormStatus","DocsTextField"] },
}
