// Generated by ../../docs_app/scripts/palette.mjs from
// ../../docs_app/palette.json — do not edit. Run `npm run palette:generate`
// in docs_app after changing the palette.

/// The dark theme's page background, for `<meta name="theme-color">`.
const themeColor = '#000000';
