// Generated by scripts/palette.mjs from palette.json — do not edit. Run `npm run palette:generate` in docs_app after changing the palette.

/** The LeanCode swatches, as `#rrggbb`. */
export const swatches = {
  /** Primary surface. LeanCode is black-first; yellow is the exception. */
  black: "#000000",
  /** Text and headings on black; the light document surface. */
  white: "#ffffff",
  /** Call to action and emphasis only. Text on it is always black. */
  ctaYellow: "#f0ff00",
  /** Body copy on dark surfaces. */
  bodyGray: "#d8d8d4",
  /** Secondary text, captions, metadata on dark. */
  mutedGray: "#a3a3a0",
  /** Secondary text, captions, metadata on light: the design system's #757575, a step darker so it also reads AA on paper. */
  mutedOnLight: "#6f6f6f",
  /** Cards and panels on black, warm-tinted. */
  surface: "#151513",
  /** A second surface step on black. */
  surface2: "#1d1d1a",
  /** The 1px hairline on white. */
  lineOnLight: "#e5e5e5",
  /** Error signal, sparingly. */
  error: "#e64239",
  /** Success signal, sparingly. */
  success: "#80c340",
  /** Site tint: a section background a step above black. */
  nearBlack: "#0a0a08",
  /** Site tint: a section background a step below white. */
  paper: "#f7f7f5",
  /** Site tint: a second surface step on white. */
  paper2: "#f2f2ef",
  /** Site tint: body copy on light surfaces. */
  bodyOnLight: "#3f3f3c",
  /** Site tint: the stronger hairline on white, for controls. */
  lineStrongOnLight: "#cfcfcb",
  /** Site tint: the CTA yellow lifted, for the primary button's hover. */
  ctaYellowLight: "#f5ff4d",
  /** Site tint: the CTA yellow as text on white, which yellow itself never is. */
  ctaYellowOnLight: "#606a00",
  /** Site tint: the error signal as text on white. */
  errorOnLight: "#be2119",
  /** Site tint: the success signal as text on white. */
  successOnLight: "#527b28",
} as const

/** The site's `--af-*` tokens per theme, as CSS colors. */
export const themes = {
  light: {
    /** Page background. */
    bg: "#ffffff",
    /** Section background: footer, code panels. */
    bg2: "#f7f7f5",
    /** Cards and frames. */
    surface: "#ffffff",
    /** Bars and chips on a surface. */
    surface2: "#f2f2ef",
    /** The hairline. */
    border: "#e5e5e5",
    /** The stronger hairline, for controls. */
    border2: "#cfcfcb",
    /** Headings and primary text. */
    text: "#000000",
    /** Body copy. */
    text2: "#3f3f3c",
    /** Captions and metadata. */
    muted: "#6f6f6f",
    /** The CTA yellow, as a fill. */
    accent: "#f0ff00",
    /** Text on the accent. */
    accentInk: "#000000",
    /** The accent as text. */
    accentText: "#606a00",
    /** The primary button's hover fill. */
    accentHover: "#f5ff4d",
    /** The accent as a wash behind icons, pills and glows. */
    accentSoft: "rgba(240, 255, 0, 0.45)",
    /** The docs' primary action fill. */
    primary: "#000000",
    /** Text on the primary fill. */
    primaryInk: "#f0ff00",
    /** The scrim behind dialogs. */
    overlay: "rgba(0, 0, 0, 0.3)",
    /** Error signal. */
    danger: "#be2119",
    /** Success signal. */
    ok: "#527b28",
  },
  dark: {
    /** Page background. */
    bg: "#000000",
    /** Section background: footer, code panels. */
    bg2: "#0a0a08",
    /** Cards and frames. */
    surface: "#151513",
    /** Bars and chips on a surface. */
    surface2: "#1d1d1a",
    /** The hairline. */
    border: "rgba(255, 255, 255, 0.12)",
    /** The stronger hairline, for controls. */
    border2: "rgba(255, 255, 255, 0.2)",
    /** Headings and primary text. */
    text: "#ffffff",
    /** Body copy. */
    text2: "#d8d8d4",
    /** Captions and metadata. */
    muted: "#a3a3a0",
    /** The CTA yellow, as a fill. */
    accent: "#f0ff00",
    /** Text on the accent. */
    accentInk: "#000000",
    /** The accent as text. */
    accentText: "#f0ff00",
    /** The primary button's hover fill. */
    accentHover: "#f5ff4d",
    /** The accent as a wash behind icons, pills and glows. */
    accentSoft: "rgba(240, 255, 0, 0.06)",
    /** The docs' primary action fill. */
    primary: "#f0ff00",
    /** Text on the primary fill. */
    primaryInk: "#000000",
    /** The scrim behind dialogs. */
    overlay: "rgba(0, 0, 0, 0.6)",
    /** Error signal. */
    danger: "#e64239",
    /** Success signal. */
    ok: "#80c340",
  },
} as const
