// Generated by scripts/palette.mjs from palette.json — do not edit. Run `npm run palette:generate` in docs_app after changing the palette.

/** The LeanCode swatches, as `#rrggbb`. */
export const swatches = {
  /** Primary surface. LeanCode is black-first; yellow is the exception. */
  black: "#000000",
  /** Text and headings on black; the light document surface. */
  white: "#ffffff",
  /** Call to action and emphasis only. Text on it is always black. */
  ctaYellow: "#f0ff00",
  /** Body copy on dark surfaces. */
  bodyGray: "#d8d8d4",
  /** Secondary text, captions, metadata on dark. */
  mutedGray: "#a3a3a0",
  /** Secondary text, captions, metadata on light: the design system's #757575, a step darker so it also reads AA on paper. */
  mutedOnLight: "#6f6f6f",
  /** Cards and panels on black, warm-tinted. */
  surface: "#151513",
  /** A second surface step on black. */
  surface2: "#1d1d1a",
  /** The 1px hairline on white. */
  lineOnLight: "#e5e5e5",
  /** Error signal, sparingly. */
  error: "#e64239",
  /** Success signal, sparingly. */
  success: "#80c340",
  /** Site tint: a section background a step above black. */
  nearBlack: "#0a0a08",
  /** Site tint: a section background a step below white. */
  paper: "#f7f7f5",
  /** Site tint: a second surface step on white. */
  paper2: "#f2f2ef",
  /** Site tint: body copy on light surfaces. */
  bodyOnLight: "#3f3f3c",
  /** Site tint: the stronger hairline on white, for controls. */
  lineStrongOnLight: "#cfcfcb",
  /** Site tint: the CTA yellow lifted, for the primary button's hover. */
  ctaYellowLight: "#f5ff4d",
  /** Site tint: the CTA yellow as text on white, which yellow itself never is. */
  ctaYellowOnLight: "#606a00",
  /** Site tint: the error signal as text on white. */
  errorOnLight: "#be2119",
  /** Site tint: the success signal as text on white. */
  successOnLight: "#527b28",
} as const

/** `#rrggbb` at an alpha, as `rgba()` — the one color form every renderer of ours understands. */
export function withAlpha(hex: string, alpha: number): string {
  const [r, g, b] = [1, 3, 5].map(i => Number.parseInt(hex.slice(i, i + 2), 16))
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

/** The site's `--af-*` tokens per theme, built from the swatches. */
export const themes = {
  light: {
    /** Page background. */
    bg: swatches.white,
    /** Section background: footer, code panels. */
    bg2: swatches.paper,
    /** Cards and frames. */
    surface: swatches.white,
    /** Bars and chips on a surface. */
    surface2: swatches.paper2,
    /** The hairline. */
    border: swatches.lineOnLight,
    /** The stronger hairline, for controls. */
    border2: swatches.lineStrongOnLight,
    /** Headings and primary text. */
    text: swatches.black,
    /** Body copy. */
    text2: swatches.bodyOnLight,
    /** Captions and metadata. */
    muted: swatches.mutedOnLight,
    /** The CTA yellow, as a fill. */
    accent: swatches.ctaYellow,
    /** Text on the accent. */
    accentInk: swatches.black,
    /** The accent as text. */
    accentText: swatches.ctaYellowOnLight,
    /** The primary button's hover fill. */
    accentHover: swatches.ctaYellowLight,
    /** The accent as a wash behind icons, pills and glows. */
    accentSoft: withAlpha(swatches.ctaYellow, 0.45),
    /** The docs' primary action fill. */
    primary: swatches.black,
    /** Text on the primary fill. */
    primaryInk: swatches.ctaYellow,
    /** The scrim behind dialogs. */
    overlay: withAlpha(swatches.black, 0.3),
    /** Error signal. */
    danger: swatches.errorOnLight,
    /** Success signal. */
    ok: swatches.successOnLight,
  },
  dark: {
    /** Page background. */
    bg: swatches.black,
    /** Section background: footer, code panels. */
    bg2: swatches.nearBlack,
    /** Cards and frames. */
    surface: swatches.surface,
    /** Bars and chips on a surface. */
    surface2: swatches.surface2,
    /** The hairline. */
    border: withAlpha(swatches.white, 0.12),
    /** The stronger hairline, for controls. */
    border2: withAlpha(swatches.white, 0.2),
    /** Headings and primary text. */
    text: swatches.white,
    /** Body copy. */
    text2: swatches.bodyGray,
    /** Captions and metadata. */
    muted: swatches.mutedGray,
    /** The CTA yellow, as a fill. */
    accent: swatches.ctaYellow,
    /** Text on the accent. */
    accentInk: swatches.black,
    /** The accent as text. */
    accentText: swatches.ctaYellow,
    /** The primary button's hover fill. */
    accentHover: swatches.ctaYellowLight,
    /** The accent as a wash behind icons, pills and glows. */
    accentSoft: withAlpha(swatches.ctaYellow, 0.06),
    /** The docs' primary action fill. */
    primary: swatches.ctaYellow,
    /** Text on the primary fill. */
    primaryInk: swatches.black,
    /** The scrim behind dialogs. */
    overlay: withAlpha(swatches.black, 0.6),
    /** Error signal. */
    danger: swatches.error,
    /** Success signal. */
    ok: swatches.success,
  },
} as const
