// Generated by docs_app/scripts/palette.mjs from docs_app/palette.json — do
// not edit. Run `npm run palette:generate` in docs_app after changing the
// palette.

import 'dart:ui' show Color;

/// The site's `--af-*` tokens for one theme, as the docs and the landing
/// page paint them.
class AfPalette {
  const AfPalette({
    required this.bg,
    required this.bg2,
    required this.surface,
    required this.surface2,
    required this.border,
    required this.border2,
    required this.text,
    required this.text2,
    required this.muted,
    required this.accent,
    required this.accentInk,
    required this.accentText,
    required this.accentHover,
    required this.accentSoft,
    required this.primary,
    required this.primaryInk,
    required this.overlay,
    required this.danger,
    required this.ok,
  });

  /// Page background.
  final Color bg;

  /// Section background: footer, code panels.
  final Color bg2;

  /// Cards and frames.
  final Color surface;

  /// Bars and chips on a surface.
  final Color surface2;

  /// The hairline.
  final Color border;

  /// The stronger hairline, for controls.
  final Color border2;

  /// Headings and primary text.
  final Color text;

  /// Body copy.
  final Color text2;

  /// Captions and metadata.
  final Color muted;

  /// The CTA yellow, as a fill.
  final Color accent;

  /// Text on the accent.
  final Color accentInk;

  /// The accent as text.
  final Color accentText;

  /// The primary button's hover fill.
  final Color accentHover;

  /// The accent as a wash behind icons, pills and glows.
  final Color accentSoft;

  /// The docs' primary action fill.
  final Color primary;

  /// Text on the primary fill.
  final Color primaryInk;

  /// The scrim behind dialogs.
  final Color overlay;

  /// Error signal.
  final Color danger;

  /// Success signal.
  final Color ok;
}

/// The light theme.
const afLight = AfPalette(
  bg: Color(0xFFFFFFFF),
  bg2: Color(0xFFF7F7F5),
  surface: Color(0xFFFFFFFF),
  surface2: Color(0xFFF2F2EF),
  border: Color(0xFFE5E5E5),
  border2: Color(0xFFCFCFCB),
  text: Color(0xFF000000),
  text2: Color(0xFF3F3F3C),
  muted: Color(0xFF757575),
  accent: Color(0xFFF0FF00),
  accentInk: Color(0xFF000000),
  accentText: Color(0xFF606A00),
  accentHover: Color(0xFFF5FF4D),
  accentSoft: Color(0x73F0FF00),
  primary: Color(0xFF000000),
  primaryInk: Color(0xFFF0FF00),
  overlay: Color(0x4D000000),
  danger: Color(0xFFBE2119),
  ok: Color(0xFF527B28),
);

/// The dark theme.
const afDark = AfPalette(
  bg: Color(0xFF000000),
  bg2: Color(0xFF0A0A08),
  surface: Color(0xFF151513),
  surface2: Color(0xFF1D1D1A),
  border: Color(0x1FFFFFFF),
  border2: Color(0x33FFFFFF),
  text: Color(0xFFFFFFFF),
  text2: Color(0xFFD8D8D4),
  muted: Color(0xFFA3A3A0),
  accent: Color(0xFFF0FF00),
  accentInk: Color(0xFF000000),
  accentText: Color(0xFFF0FF00),
  accentHover: Color(0xFFF5FF4D),
  accentSoft: Color(0x0FF0FF00),
  primary: Color(0xFFF0FF00),
  primaryInk: Color(0xFF000000),
  overlay: Color(0x99000000),
  danger: Color(0xFFE64239),
  ok: Color(0xFF80C340),
);
