#!/usr/bin/env node
/*
 * AI-Provenance:
 *   model: Claude Fable 5.1
 *   harness: Claude Code
 */

/**
 * Writes every copy of the site's palette from palette.json, so the landing
 * page, the docs, the social cards, the Flutter demos and the logos cannot
 * disagree about a color. palette.json names the LeanCode swatches and maps
 * them onto the `--af-*` tokens of the light and dark themes; this script
 * turns that into each consumer's language.
 *
 *   generate  write the generated files and recolor the marked SVG elements
 *   check     fail if any of them differs from what palette.json says
 *
 * Generated (committed, so every checkout builds without running this):
 *   app/af-tokens.css                            the tokens as CSS variables, for the docs' stylesheet
 *   lib/palette.generated.ts                     the swatches and tokens for the OG cards and the logo
 *   flutter/lib/support/palette.generated.dart   the swatches and tokens as Flutter Colors, for the live demos
 *   ../landing/lib/palette.generated.dart        the same as Jaspr Colors; the landing page writes its
 *                                                `--af-*` variables and theme-color from it at build time
 *
 * Recolored in place: SVG elements carrying `data-palette="<swatch>"` get that
 * swatch as their fill. The logos and icons stay single files of artwork; the
 * attribute marks which shapes are brand color.
 */
import { readFile, writeFile } from "node:fs/promises"
import { join, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const docsApp = resolve(fileURLToPath(new URL(".", import.meta.url)), "..")
const repoRoot = resolve(docsApp, "..")
const landing = join(repoRoot, "landing")
const sourceFile = join(docsApp, "palette.json")

const palette = JSON.parse(await readFile(sourceFile, "utf8"))
const tokenNames = Object.keys(palette.tokens)

for (const [theme, tokens] of Object.entries(palette.themes)) {
  const missing = tokenNames.filter(name => !(name in tokens))
  const extra = Object.keys(tokens).filter(name => !(name in palette.tokens))
  if (missing.length || extra.length) {
    throw new Error(
      `palette.json: theme "${theme}" must define exactly the tokens listed under "tokens"` +
        (missing.length ? `; missing ${missing.join(", ")}` : "") +
        (extra.length ? `; unknown ${extra.join(", ")}` : ""),
    )
  }
}

// ---------- Colors ----------

function swatch(name) {
  const entry = palette.swatches[name]
  if (!entry) throw new Error(`palette.json: unknown swatch "${name}"`)
  if (!/^#[0-9a-f]{6}$/.test(entry.hex)) throw new Error(`palette.json: swatch "${name}" must be lowercase #rrggbb`)
  return entry
}

/** A token's value: the swatch's hex, and the alpha it is used at (1 for solid). */
function color(value) {
  return typeof value === "string"
    ? { hex: swatch(value).hex, alpha: 1 }
    : { hex: swatch(value.of).hex, alpha: value.alpha }
}

const channels = hex => [1, 3, 5].map(i => Number.parseInt(hex.slice(i, i + 2), 16))

const cssColor = ({ hex, alpha }) => (alpha === 1 ? hex : `rgba(${channels(hex).join(", ")}, ${alpha})`)

const cssName = name => `--af-${name.replaceAll(/([a-z])([A-Z0-9])/g, "$1-$2").toLowerCase()}`

// ---------- Outputs ----------

const doNotEdit = (from, here) =>
  `Generated by ${from} from ${here} — do not edit. Run \`npm run palette:generate\` in docs_app after changing the palette.`

/** The same notice, wrapped for Dart's 80 columns. */
const dartHeader = lines => lines.map(line => `// ${line}\n`).join("")

/** `text` as a Dart doc comment at `indent`, wrapped to 80 columns. */
function doc(text, indent = "  ") {
  const width = 80 - indent.length - "/// ".length
  const lines = []
  let line = ""
  for (const word of text.split(" ")) {
    if (line && line.length + 1 + word.length > width) {
      lines.push(line)
      line = word
    } else {
      line = line ? `${line} ${word}` : word
    }
  }
  if (line) lines.push(line)
  return lines.map(l => `${indent}/// ${l}\n`).join("")
}

function tokensCss() {
  const block = (selector, tokens, notes) =>
    `${selector} {\n` +
    tokenNames
      .map(
        name =>
          `${notes ? `  /* ${palette.tokens[name]} */\n` : ""}  ${cssName(name)}: ${cssColor(color(tokens[name]))};\n`,
      )
      .join(notes ? "\n" : "") +
    "}\n"
  return (
    `/* ${doNotEdit("docs_app/scripts/palette.mjs", "docs_app/palette.json")} */\n\n` +
    block(":root", palette.themes.light, true) +
    "\n" +
    block(".dark", palette.themes.dark, false)
  )
}

function paletteTs() {
  const swatches = Object.entries(palette.swatches)
    .map(([name, { hex, note }]) => `  /** ${note} */\n  ${name}: "${hex}",\n`)
    .join("")
  const theme = tokens =>
    tokenNames
      .map(name => `    /** ${palette.tokens[name]} */\n    ${name}: "${cssColor(color(tokens[name]))}",\n`)
      .join("")
  return (
    `// ${doNotEdit("scripts/palette.mjs", "palette.json")}\n\n` +
    `/** The LeanCode swatches, as \`#rrggbb\`. */\n` +
    `export const swatches = {\n${swatches}} as const\n\n` +
    `/** The site's \`--af-*\` tokens per theme, as CSS colors. */\n` +
    `export const themes = {\n` +
    `  light: {\n${theme(palette.themes.light)}  },\n` +
    `  dark: {\n${theme(palette.themes.dark)}  },\n` +
    `} as const\n`
  )
}

/**
 * The palette as Dart: `enum Palette` names the swatches, `AfTheme` holds one
 * theme's tokens, and `afLight`/`afDark` build them from the enum — the same
 * shape ciach's landing page uses. `members` are the enum's color accessors,
 * which differ between Flutter's and Jaspr's `Color`; `themeMembers` are extra
 * members of `AfTheme`.
 */
function dart({ header, import: importLine, members, themeMembers = "", trailer = "" }) {
  const swatches = Object.entries(palette.swatches)
    .map(([name, { hex, note }]) => `${doc(note)}  ${name}(0x${hex.slice(1)}),\n`)
    .join("\n")
    .replace(/,\n$/, ";\n")
  const fields = tokenNames.map(name => `${doc(palette.tokens[name])}  final Color ${name};\n`).join("\n")
  const params = tokenNames.map(name => `    required this.${name},\n`).join("")
  const theme = tokens =>
    tokenNames
      .map(name => {
        const value = tokens[name]
        const swatch =
          typeof value === "string" ? `Palette.${value}.color` : `Palette.${value.of}.alpha(${value.alpha})`
        return `  ${name}: ${swatch},\n`
      })
      .join("")
  return (
    dartHeader(header) +
    `\n${importLine}\n\n` +
    `/// The LeanCode swatches, as \`palette.json\` names them, each a packed\n` +
    `/// \`0xRRGGBB\`.\n` +
    `enum Palette {\n${swatches}\n` +
    `  const Palette(this.rgb);\n\n` +
    `  final int rgb;\n\n` +
    `${members}}\n\n` +
    `/// The site's \`--af-*\` tokens for one theme, as the docs and the landing\n` +
    `/// page paint them.\n` +
    `class AfTheme {\n` +
    `  const AfTheme({\n${params}  });\n\n` +
    `${fields}${themeMembers}}\n\n` +
    `/// The light theme.\n` +
    `final afLight = AfTheme(\n${theme(palette.themes.light)});\n\n` +
    `/// The dark theme.\n` +
    `final afDark = AfTheme(\n${theme(palette.themes.dark)});\n` +
    trailer
  )
}

function flutterDart() {
  return dart({
    header: [
      "Generated by docs_app/scripts/palette.mjs from docs_app/palette.json — do",
      "not edit. Run `npm run palette:generate` in docs_app after changing the",
      "palette.",
    ],
    import: "import 'dart:ui' show Color;",
    members:
      `  Color get color => Color(0xff000000 | rgb);\n\n` +
      `  /// \`#rrggbb\`.\n` +
      `  String get hex => '#\${rgb.toRadixString(16).padLeft(6, '0')}';\n\n` +
      `  Color alpha(double alpha) => color.withValues(alpha: alpha);\n`,
  })
}

function landingDart() {
  return dart({
    header: [
      "Generated by ../../docs_app/scripts/palette.mjs from",
      "../../docs_app/palette.json — do not edit. Run `npm run palette:generate`",
      "in docs_app after changing the palette.",
    ],
    import: "import 'package:jaspr/dom.dart';",
    members:
      `  Color get color => Color.value(rgb);\n\n` +
      `  /// \`#rrggbb\`.\n` +
      `  String get hex => color.value;\n\n` +
      `  Color alpha(double alpha) =>\n` +
      `      Color.rgba(rgb >> 16 & 0xff, rgb >> 8 & 0xff, rgb & 0xff, alpha);\n`,
    themeMembers:
      `\n  /// The theme as the \`--af-*\` custom properties the stylesheet reads.\n` +
      `  Map<String, Color> get cssVariables => {\n` +
      tokenNames.map(name => `    '${cssName(name)}': ${name},\n`).join("") +
      `  };\n`,
    trailer:
      `\n/// The dark theme's page background, for \`<meta name="theme-color">\`.\n` +
      `final themeColor = afDark.bg.value;\n`,
  })
}

/** Recolors the elements of an SVG that carry `data-palette="<swatch>"`. */
function recolorSvg(file, svg) {
  let marked = 0
  const result = svg.replaceAll(/<[a-zA-Z][^>]*\bdata-palette="([^"]+)"[^>]*>/g, (tag, name) => {
    marked += 1
    if (!/\bfill="[^"]*"/.test(tag)) throw new Error(`${file}: the element marked data-palette="${name}" has no fill`)
    return tag.replace(/\bfill="[^"]*"/, `fill="${swatch(name).hex}"`)
  })
  if (marked === 0) throw new Error(`${file}: no element carries data-palette; mark the brand-color shapes`)
  return result
}

const generated = [
  { file: join(docsApp, "app", "af-tokens.css"), content: tokensCss },
  { file: join(docsApp, "lib", "palette.generated.ts"), content: paletteTs },
  { file: join(docsApp, "flutter", "lib", "support", "palette.generated.dart"), content: flutterDart },
  { file: join(landing, "lib", "palette.generated.dart"), content: landingDart },
]

const svgs = [
  join(docsApp, "app", "icon.svg"),
  join(docsApp, "public", "logo-dark.svg"),
  join(docsApp, "public", "logo-light.svg"),
  join(landing, "web", "landing-icon.svg"),
]

/** Every output with what it should contain and what it contains now. */
async function outputs() {
  const current = async file => {
    try {
      return await readFile(file, "utf8")
    } catch (error) {
      if (error.code === "ENOENT") return null
      throw error
    }
  }
  const files = []
  for (const { file, content } of generated) {
    files.push({ file, expected: content(), actual: await current(file) })
  }
  for (const file of svgs) {
    const actual = await current(file)
    if (actual === null) throw new Error(`${file} is missing`)
    files.push({ file, expected: recolorSvg(relative(repoRoot, file), actual), actual })
  }
  return files
}

const label = file => relative(repoRoot, file)

async function generate() {
  for (const { file, expected, actual } of await outputs()) {
    if (expected === actual) continue
    await writeFile(file, expected)
    console.log(`wrote ${label(file)}`)
  }
  console.log(`palette: ${generated.length} generated files and ${svgs.length} SVGs follow palette.json`)
}

async function check() {
  const files = await outputs()
  const stale = files.filter(({ expected, actual }) => expected !== actual)
  if (stale.length === 0) {
    console.log(`palette: ${generated.length} generated files and ${svgs.length} SVGs are up to date`)
    return
  }
  throw new Error(
    "The palette's generated files are out of date — run `npm run palette:generate` in docs_app:\n" +
      stale.map(({ file }) => `  ${label(file)}`).join("\n"),
  )
}

const command = process.argv[2]
try {
  if (command === "generate") await generate()
  else if (command === "check") await check()
  else throw new Error("usage: node scripts/palette.mjs <generate|check>")
} catch (error) {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
}
